# Generated by Django 4.0.6 on 2024-12-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='availability',
            field=models.ManyToManyField(to='user_system.day'),
        ),
    ]
