# Generated by Django 5.1.2 on 2024-11-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
