# Generated by Django 4.0.6 on 2024-11-17 16:10

from django.db import migrations

def populate_days(apps, schema_editor):
    Day = apps.get_model('user_system', 'Day')
    days_of_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    for day_name in days_of_week:
        Day.objects.create(day=day_name)

class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0002_day_user_availability'),
    ]

    operations = [
        migrations.RunPython(populate_days),
    ]
