# Generated by Django 4.0.6 on 2024-11-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0003_auto_20241117_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
