# Generated by Django 4.0.6 on 2024-12-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0005_user_student_max_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_max_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, help_text='Enter the maximum hourly rate you are willing to pay, in GBP.', max_digits=6, null=True),
        ),
    ]
