# Generated by Django 4.0.6 on 2024-11-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0006_knowledgearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter your hourly rate in GBP.', max_digits=6, null=True),
        ),
    ]
