# Generated by Django 4.0.6 on 2024-12-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0006_alter_user_student_max_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, help_text='Enter your hourly rate in GBP.', max_digits=6, null=True),
        ),
    ]
