# Generated by Django 4.0.6 on 2024-12-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0007_alter_user_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Enter your hourly rate in GBP.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_max_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Enter the maximum hourly rate you are willing to pay, in GBP.', max_digits=6, null=True),
        ),
    ]
