# Generated by Django 4.0.6 on 2024-11-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
