# Generated by Django 4.0.6 on 2024-11-24 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0002_invoice_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='location',
        ),
    ]
