# Generated by Django 4.0.6 on 2024-11-24 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0004_invoice_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='location',
        ),
    ]
