# Generated by Django 4.0.6 on 2024-11-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0005_remove_invoice_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
