# Generated by Django 4.0.6 on 2024-11-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0007_remove_invoice_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
