# Generated by Django 4.0.6 on 2024-12-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0008_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
