# Generated by Django 4.0.6 on 2024-12-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0009_invoice_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='location',
        ),
    ]
