# Generated by Django 5.1.2 on 2024-11-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='Admin', max_length=20),
            preserve_default=False,
        ),
    ]
