# Generated by Django 4.0.6 on 2024-12-11 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_venues(apps, schema_editor):
    Venue = apps.get_model('request_handler', 'Venue')
    venues = ['In Person', 'Online', 'No Preference']
    for venue in venues:
        Venue.objects.create(venue=venue)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_system', '0001_initial'),
        ('invoicer', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated', models.BooleanField(blank=True, default=False)),
                ('knowledge_area', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('late', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('rejected_request', models.BooleanField(default=False, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                          related_name='allocated_day', to='user_system.day')),
                ('day2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='allocated_day2', to='user_system.day')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              related_name='request_invoice', to='invoicer.invoice')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='student', to=settings.AUTH_USER_MODEL)),
                ('tutor',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='tutor', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='allocated_venue', to='request_handler.venue')),
                ('venue_preference',
                 models.ManyToManyField(related_name='student_venue_preference', to='request_handler.venue')),
            ],
        ),
        migrations.RunPython(populate_venues),
        migrations.AddField(
            model_name='request',
            name='group_request_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='request',
            name='rejected_request',
            field=models.BooleanField(default=False),
        ),
    ]
