# Generated by Django 4.0.6 on 2024-12-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='group_request_id',
            field=models.IntegerField(default=-1),
        ),
    ]
