# Generated by Django 5.1.2 on 2024-11-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='student_email',
        ),
        migrations.AlterField(
            model_name='request',
            name='duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='frequency',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='knowledge_area',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='term',
            field=models.CharField(max_length=255),
        ),
    ]
