# Generated by Django 4.0.6 on 2024-11-17 16:12

from django.db import migrations

def populate_modes(apps, schema_editor):
    Venue = apps.get_model('request_handler', 'Venue')
    venues = ['In Person', 'Online', 'No Preference']
    for venue in venues:
        Venue.objects.create(venue=venue)

class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_modes)
    ]
