# Generated by Django 4.0.6 on 2024-12-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0002_request_group_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='rejected_request',
            field=models.BooleanField(default=False),
        ),
    ]
