# Generated by Django 4.0.6 on 2024-11-18 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0003_auto_20241117_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='availability',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
