# Generated by Django 4.0.6 on 2024-11-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0003_auto_20241117_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='late',
            field=models.BooleanField(default=False),
        ),
    ]
