# Generated by Django 5.1.2 on 2024-11-05 18:44

from django.db import migrations

def populate_days(apps, schema_editor):
    Day = apps.get_model('request_handler', 'Day')
    days_of_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    for day_name in days_of_week:
        Day.objects.create(day=day_name)


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0004_alter_request_student'),
    ]

    operations = [
        migrations.RunPython(populate_days),
    ]
