# Generated by Django 4.0.6 on 2024-11-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0004_request_late'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
