# Generated by Django 4.0.6 on 2024-11-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0004_remove_request_availability_delete_day'),
        ('request_handler', '0005_request_is_recurring'),
    ]

    operations = [
    ]
