# Generated by Django 4.0.6 on 2024-11-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0005_remove_request_late_request_is_recurring'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='late',
            field=models.BooleanField(default=False),
        ),
    ]
