# Generated by Django 5.1.2 on 2024-11-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0005_auto_20241105_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='venue_preference',
            field=models.ManyToManyField(to='request_handler.modality'),
        ),
    ]
