# Generated by Django 5.1.2 on 2024-11-05 19:15

from django.db import migrations

def populate_modes(apps, schema_editor):
    Modality = apps.get_model('request_handler', 'Modality')
    modes = ['In Person', 'Online', 'No Preference']
    for mode in modes:
        Modality.objects.create(mode=mode)

class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0006_modality_request_venue_preference'),
    ]

    operations = [
        migrations.RunPython(populate_modes)
    ]
