# Generated by Django 4.0.6 on 2024-11-18 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_system', '0003_auto_20241117_1610'),
        ('request_handler', '0006_merge_20241118_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_day', to='user_system.day'),
        ),
        migrations.AddField(
            model_name='request',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_venue', to='request_handler.venue'),
        ),
        migrations.AlterField(
            model_name='request',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='tutor',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='venue_preference',
            field=models.ManyToManyField(related_name='student_venue_preference', to='request_handler.venue'),
        ),
    ]
