# Generated by Django 4.0.6 on 2024-11-19 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request_handler', '0007_request_day_request_venue_alter_request_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='tutor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
