# Generated by Django 4.0.6 on 2024-11-23 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0002_invoice_location'),
        ('request_handler', '0008_alter_request_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_invoice', to='invoicer.invoice'),
        ),
    ]
