# Generated by Django 4.0.6 on 2024-12-06 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0008_alter_user_hourly_rate_alter_user_student_max_rate'),
        ('request_handler', '0009_request_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='day2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_day2', to='user_system.day'),
        ),
    ]
