# Generated by Django 4.0.6 on 2024-11-26 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_system', '0004_alter_day_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request_handler', '0009_request_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_area', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=255, null=True)),
                ('frequency', models.CharField(default='Weekly', max_length=255, null=True)),
                ('duration', models.CharField(default='1h', max_length=255)),
                ('late', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_allocated_day', to='user_system.day')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_student', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_tutor', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_allocated_venue', to='request_handler.venue')),
                ('venue_preference', models.ManyToManyField(related_name='booking_student_venue_preference', to='request_handler.venue')),
            ],
        ),
    ]
