# Generated by Django 4.0.6 on 2024-11-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0009_alter_request_allocated_alter_request_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='late',
            field=models.BooleanField(default=False),
        ),
    ]
