# Generated by Django 4.0.6 on 2024-11-27 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0010_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='late',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
