# Generated by Django 4.0.6 on 2024-12-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0011_request_rejected_request_request_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='rejected_request',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
