# Generated by Django 4.0.6 on 2024-11-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_scheduler', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='venue_preference',
        ),
    ]
