# Generated by Django 4.0.6 on 2024-11-29 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_scheduler', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 12, 0)),
        ),
        migrations.AddField(
            model_name='booking',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 12, 0)),
        ),
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.CharField(default='Tutor session', max_length=255),
        ),
    ]
