# Generated by Django 4.0.6 on 2024-11-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_scheduler', '0003_booking_end_booking_start_booking_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lesson_identifier',
            field=models.IntegerField(default=-1),
        ),
    ]
