# Generated by Django 4.0.6 on 2024-11-28 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request_handler', '0009_request_invoice'),
        ('calendar_scheduler', '0003_remove_booking_venue_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_allocated_venue', to='request_handler.venue'),
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
