# Generated by Django 4.0.6 on 2024-12-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_scheduler', '0004_booking_lesson_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_requested',
            field=models.BooleanField(default=False),
        ),
    ]
