# Generated by Django 4.0.6 on 2024-12-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_scheduler', '0005_booking_cancellation_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start',
        ),
    ]
